### ISSUE TITLE
CometD

### ISSUE THREAD

**Issue by wardjm** [dxFeed/dxfeed-c-api#100]
I'm trying to connect to a CometD endpoint, and it either hangs or double frees and crashes (possibly when it tries to deinit a session that never got made?), depending on how I'm trying to do it. It's hard to give a test case to recreate the issue since it requires an auth token. Is this type of connection fundamentally different and not supported? I even tried just using the CommandLine api test code to connect and it hangs there too.

**Comment by Strotsev** [comment]
Hello, @wardjm!
The Java/C/.NET/Python APIs is designed to work with the QD endpoints.
Working with CometD endpoints is supported only by the [JS API](https://github.com/dxFeed/dxfeed-js-api). 
Please send us the address of the CometD endpoint you want to connect to and we'll prepare a code snippet for you.

**Comment by wardjm** [comment]
Thanks!

https://tasty-live-web.dxfeed.com/live/cometd

**Comment by Strotsev** [comment]
@wardjm the best way to track progress is via ticket on the [Service Desk portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1).
Please create it and also attach your authentication token to the ticket.

**Comment by wardjm** [comment]
Wait, I'm sorry. What exactly is being produced? Is it the C code for CometD? I can coble together something using the JS API on my own.

**Comment by Strotsev** [comment]
Hello, @wardjm 
Sorry for the delay. Unfortunately, there is no official cometd library for C, so we suggest using JS for this purpose.
We can help with a simple JS example.

Regarding the endpoint that you plan to use, make sure that you do not violate the rights of the platform that provided you with this address. Otherwise, they have every reason to "freeze" your account.
